-- MySQL Script generated by MySQL Workbench
-- Fri Oct 16 23:26:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectbeer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectbeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectbeer` DEFAULT CHARACTER SET utf8 ;
USE `projectbeer` ;

-- -----------------------------------------------------
-- Table `projectbeer`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbeer`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectbeer`.`Promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbeer`.`Promotions` (
  `idPromotions` INT NULL AUTO_INCREMENT,
  `reduction` TINYINT(3) NULL,
  `debut` DATETIME NULL,
  `fin` DATETIME NULL,
  PRIMARY KEY (`idPromotions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectbeer`.`Style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbeer`.`Style` (
  `idStyle` INT NOT NULL AUTO_INCREMENT,
  `Fabrication` VARCHAR(45) NULL,
  PRIMARY KEY (`idStyle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectbeer`.`bieres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbeer`.`bieres` (
  `idbieres` INT NOT NULL AUTO_INCREMENT,
  `nombiere` VARCHAR(155) NULL,
  `pourcentage` DECIMAL(3,2) NULL,
  `Brasserie` VARCHAR(45) NULL,
  `prix` DECIMAL(3,2) NULL,
  `Promotions_idPromotions` INT NOT NULL,
  `Style_idStyle` INT NOT NULL,
  PRIMARY KEY (`idbieres`),
  INDEX `fk_bieres_Promotions1_idx` (`Promotions_idPromotions` ASC),
  INDEX `fk_bieres_Style1_idx` (`Style_idStyle` ASC),
  CONSTRAINT `fk_bieres_Promotions1`
    FOREIGN KEY (`Promotions_idPromotions`)
    REFERENCES `projectbeer`.`Promotions` (`idPromotions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bieres_Style1`
    FOREIGN KEY (`Style_idStyle`)
    REFERENCES `projectbeer`.`Style` (`idStyle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectbeer`.`couleurbière`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbeer`.`couleurbière` (
  `idcategoriebière` INT NOT NULL AUTO_INCREMENT,
  `Couleurbière` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoriebière`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectbeer`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbeer`.`images` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `legende` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `bieres_idbieres` INT NOT NULL,
  PRIMARY KEY (`idimages`),
  INDEX `fk_images_bieres1_idx` (`bieres_idbieres` ASC),
  CONSTRAINT `fk_images_bieres1`
    FOREIGN KEY (`bieres_idbieres`)
    REFERENCES `projectbeer`.`bieres` (`idbieres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
